#!/bin/sh
set -e

if ! getent passwd wildfly >/dev/null; then
        adduser --quiet --system --no-create-home --home /opt/wildfly --shell /usr/sbin/nologin wildfly
fi

if [ -x "/etc/init.d/wildfly" ] || [ -e "/etc/init/wildfly.conf" ]; then
        if [ ! -e "/etc/init/wildfly.conf" ]; then
                update-rc.d wildfly defaults >/dev/null
        fi
        invoke-rc.d wildfly start || exit $?
fi
